channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pysam=0.15.4
  - python=3.7.6
  - samtools=1.9
  - seqtk=1.3
  - grep=2.14
  - r=3.6
  - r-ggplot2=3.2.1
  - r-ape=5.3
  - r-reshape2=1.4.3
  - r-gridextra=2.3
